# Site Build Settings

url: "https://www.pratheba.com" # the base hostname & protocol for your site, e.g. http://example.com
# jekyll-paginate configuration
paginate: 10

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink: :title/
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "Pratheba's blog"
description: "என் பக்கம்.."
tagline: "என் பக்கம்.."
author: "Pratheba Chandramohan"
website: https://www.pratheba.com

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
fbcomments: yes
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/content/images/2017/10/cover.jpg

